//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int address_id { get; set; }
        public int person_id { get; set; }
        public string description { get; set; }
        public string street_address { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string zipcode { get; set; }
        public string country_code { get; set; }
    
        public virtual country country { get; set; }
        public virtual person person { get; set; }
    }
}
