//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClientsEntities : DbContext
    {
        public ClientsEntities()
            : base("name=ClientsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<comment_like> comment_like { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<friendlink> friendlinks { get; set; }
        public virtual DbSet<like> likes { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<person> persons { get; set; }
        public virtual DbSet<picture> pictures { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
