//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comment()
        {
            this.comment_like = new HashSet<comment_like>();
        }
    
        public int comment_id { get; set; }
        public int picture_id { get; set; }
        public int person_id { get; set; }
        public string comment1 { get; set; }
        public string timestamp { get; set; }
        public bool read { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment_like> comment_like { get; set; }
        public virtual person person { get; set; }
        public virtual picture picture { get; set; }
    }
}
